// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKKfWgQxHWwU3Q66f1qhMbvBoliKITqD8',
    appId: '1:834700072559:web:2f8dd21671c138c6f2df9a',
    messagingSenderId: '834700072559',
    projectId: 'quiz-app-f3a75',
    authDomain: 'quiz-app-f3a75.firebaseapp.com',
    storageBucket: 'quiz-app-f3a75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmvC-ij8e8S3nFHDRZv-MvMgNtDdHuavA',
    appId: '1:834700072559:android:f2717616db051c74f2df9a',
    messagingSenderId: '834700072559',
    projectId: 'quiz-app-f3a75',
    storageBucket: 'quiz-app-f3a75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSmA1c4CcRsjERAgDZSIXbq5-z5Ib3XM',
    appId: '1:834700072559:ios:34ce8ff405f1006af2df9a',
    messagingSenderId: '834700072559',
    projectId: 'quiz-app-f3a75',
    storageBucket: 'quiz-app-f3a75.firebasestorage.app',
    iosClientId: '834700072559-7d1a4tjh9ffjiksapu8omgggiir6kfgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuSmA1c4CcRsjERAgDZSIXbq5-z5Ib3XM',
    appId: '1:834700072559:ios:34ce8ff405f1006af2df9a',
    messagingSenderId: '834700072559',
    projectId: 'quiz-app-f3a75',
    storageBucket: 'quiz-app-f3a75.firebasestorage.app',
    iosClientId: '834700072559-7d1a4tjh9ffjiksapu8omgggiir6kfgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKKfWgQxHWwU3Q66f1qhMbvBoliKITqD8',
    appId: '1:834700072559:web:33e5fedd9e1bf510f2df9a',
    messagingSenderId: '834700072559',
    projectId: 'quiz-app-f3a75',
    authDomain: 'quiz-app-f3a75.firebaseapp.com',
    storageBucket: 'quiz-app-f3a75.firebasestorage.app',
  );
}
